### PR TITLE
Display user/organization in email subject

### PR DESCRIPTION
**Pull request by crazy-max**
Orig #39

### CODE REVIEW

**Comment by crazy-max** [comment]
Hi @vfeskov, according to [RFC 2822](http://www.faqs.org/rfcs/rfc2822.html), section 2.1.1 :

> There are two limits that this standard places on the number of characters in a line. Each line of characters MUST be no more than 998 characters, and SHOULD be no more than 78 characters, excluding the CRLF.

So we cannot go up 78 characters for email subject but :
* Git branch/tag name can have up to 255 characters.
* GitHub limit the user/org and repo name up to 100 characters.

After observation we can therefore conclude that we can potentially arrive at a number of 355 characters today in the email subject or 455 if you merge my PR (+100 for org/user).

I think we can deal with this with a ratio limitation of chars for `org|user`, `repo`, `tag` :
* `org|user` : 22 max
* `repo` : 22 max
* `repo` : 34 max

What do you think ?

**Comment by vfeskov** [comment]
@crazy-max i did not mean that there was technical limitation on subject length, so far i've been sending emails with huge subjects and not getting them bounced from any mail server

Problem lies in UX: since a lot of repos actually have fully contained names, e.g. `angular` or `react`, there's no value in specifying the org name for those but they do extend subject significantly, and longer subjects are harder to digest

what i suggest is when making a subject to use a constant array, that would contain names of those special repos with generic names, e.g., `const GENERIC_REPO_NAMES = ['core', 'server', 'util']`. I would fill it with more repos according to the data I have in the db

**Comment by crazy-max** [comment]
Oh ok, LGTM :)

**Comment by crazy-max** [comment]
Maybe also add a bool flag to force `org` by user ?

**Comment by crazy-max** [comment]
We can close it now

**Pull request closed without merging**
